apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: artifactory-download-image
    newName: artifactory-download
    newTag: latest

namespace: artifactory

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: artifactory-download
