apiVersion: v1
kind: Service
metadata:
  name: artifactory-download
  namespace: artifactory
spec:
  selector:
    app: artifactory-download
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP